# Generated by Django 2.2.16 on 2021-01-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichefrais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etat',
            name='libelle',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='etat',
            name='id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
